apiVersion: apps/v1
kind: Deployment
metadata:
  name: go-api
  namespace: apps
spec:
  selector:
    matchLabels:
      app: go-api
  template:
    metadata:
      labels:
        app: go-api
    spec:
      containers:
        - name: go-api
          image: jdnielss/go-api-service:v1
          resources:
            limits:
              memory: "128Mi"
              cpu: "50m"
          ports:
            - containerPort: 8080
