apiVersion: apps/v1
kind: Deployment
metadata:
  name: go-api
  namespace: apps
spec:
  selector:
    matchLabels:
      app: go-api
  replicas: 2
  template:
    metadata:
      labels:
        app: go-api
    spec:
      containers:
        - name: go-api
          image: jdnielss/go-api:v1
          envFrom:
            - configMapRef:
                name: go-environment
          resources:
            limits:
              memory: "10Mi"
              cpu: "10m"
          ports:
            - containerPort: 8080
