apiVersion: apps/v1
kind: Deployment
metadata:
  name: go-api
  namespace: apps
spec:
  selector:
    matchLabels:
      app: go-api
  template:
    metadata:
      labels:
        app: go-api
    spec:
      containers:
        - name: go-api
          image: docker.io/jdnielss/golang-api-service:v1.0 # {"$imagepolicy": "flux-system:go-api-service"}
          resources:
            limits:
              memory: "128Mi"
              cpu: "50m"
          ports:
            - containerPort: 8080
      imagePullSecrets:
        - name: dockerhub-credential
