apiVersion: apps/v1
kind: Deployment
metadata:
  name: go-api-service
  namespace: apps
spec:
  selector:
    matchLabels:
      app: go-api-service
  template:
    metadata:
      labels:
        app: go-api-service
    spec:
      containers:
        - name: go-api-service
          image: docker.io/jdnielss/go-api-service:1.5.4 # {"$imagepolicy": "flux-system:go-api-service"}
          resources:
            limits:
              memory: "128Mi"
              cpu: "50m"
          ports:
            - containerPort: 8080
