apiVersion: v1
kind: Service
metadata:
  name: go-api-service
  namespace: apps
spec:
  selector:
    app: go-api-service
  ports:
    - name: http
      port: 8080
      targetPort: 8080
      protocol: TCP
