apiVersion: image.toolkit.fluxcd.io/v1beta1
kind: ImageUpdateAutomation
metadata:
  name: go-api
  namespace: default
spec:
  interval: 1m0s
  sourceRef:
    kind: GitRepository
    name: go-api
  git:
    checkout:
      ref:
        branch: master
    commit:
      author:
        email: mail.jdnielss@gmail.com
        name: fluxcdbot
      messageTemplate: "{{range .Updated.Images}}{{println .}}{{end}}"
    push:
      branch: master
  update:
    path: ./api/deployment.yaml
    strategy: Setters
