apiVersion: image.toolkit.fluxcd.io/v1beta2
kind: ImagePolicy
metadata:
  name: go-api-service
  namespace: default
spec:
  imageRepositoryRef:
    name: go-api-service
  policy:
    semver:
      range: "v1.10"
