apiVersion: v1
kind: Service
metadata:
  name: profile-kube
  namespace: apps
spec:
  selector:
    app: profile-kube
  ports:
    - name: http
      port: 80
      targetPort: 80
      protocol: TCP
